### ISSUE TITLE
右键菜单消失了？？

### ISSUE THREAD

**Issue by iir910** [rejerry/bookmark#10]
扩展版本 (extension version): 1.0.1.705

之前的版本有右键菜单的。

**Comment by jerrytci** [comment]
是的。
抱歉，用快捷键（地址栏输入：chrome://extensions/shortcuts）暂时代替右键菜单功能
初步判断和版本无关
问题还在查找中

**Comment by jerrytci** [comment]
已经修复了，静待一两天。修复版本：1.0.1.8190

**Comment by iir910** [comment]
好的。点赞。

keeppatient ***@***.***> 于2021年8月19日周四 下午10:25写道：

**Comment by jerrytci** [comment]
had fixed
已修复
