### ISSUE TITLE
希望添加一个一键保存当前所有打开标签的功能

### ISSUE THREAD

**Issue by hokkhitsu** [rejerry/bookmark#3]
希望能一键保存所有标签

**Comment by jerrytci** [comment]
点击标题就可以打开所有标签

**Comment by hokkhitsu** [comment]
我不是想打开。我是想点击右上角的拓展按钮就能储存所有标签到 ***临时书签***。

**Comment by jerrytci** [comment]
> 我不是想打开。我是想点击右上角的拓展按钮就能储存所有标签到 _**临时书签**_。

好的，已加入todo

**Comment by hokkhitsu** [comment]
![image](https://user-images.githubusercontent.com/30873231/55334283-8a7c3180-54cb-11e9-98aa-25fc2c81e6db.png)
在onetab中，一按这个图标， 所有当前标签就会保存到onetab页面（并关闭）。
我看到你有点击右键然后保存所有标签的功能，但是这个感觉总是差了些什么。
目前你点击图标是打开（或跳到）  **bookmark** 标签，如果能让用户选择，是否同时  **关闭并存储所有标签** 似乎方便些。

**Comment by jerrytci** [comment]
> ![image](https://user-images.githubusercontent.com/30873231/55334283-8a7c3180-54cb-11e9-98aa-25fc2c81e6db.png)
> 在onetab中，一按这个图标， 所有当前标签就会保存到onetab页面（并关闭）。
> 我看到你有点击右键然后保存所有标签的功能，但是这个感觉总是差了些什么。
> 目前你点击图标是打开（或跳到） **bookmark** 标签，如果能让用户选择，是否同时 **关闭并存储所有标签** 似乎方便些。

右键图标选项可以设置
