### ISSUE TITLE
[New Feature]书签的导入导出

### ISSUE THREAD

**Issue by hokkhitsu** [rejerry/bookmark#4]
目前既然没有云同步的话，希望增加书签的导入导出功能，以便跨设备使用之需。

**Comment by jerrytci** [comment]
> 目前既然没有云同步的话，希望增加书签的导入导出功能，以便跨设备使用之需。

所有的书签都是保存到google账户的（就是云同步了），在chrome书签的 "其他文件夹里" / “Other folders”。
