### ISSUE TITLE
本地编译失败，求指点

### ISSUE THREAD

**Issue by gclm** [rejerry/bookmark#8]
![](https://cdn.jsdelivr.net/gh/gclm/images@master/2019121018444ZpLri.png)

**Comment by jerrytci** [comment]
别用yarn build，用yarn dev 才可以。

**Comment by jerrytci** [comment]
已重新上线
https://chrome.google.com/webstore/detail/bookmark/paigdnkkmodopofccgdeacgoocgeijkn/related?hl=zh-CN&authuser=0
