### ISSUE TITLE
连不上了，老哥，看图片还蛮想用的

### ISSUE THREAD

**Issue by Metro2033-Max** [rejerry/bookmark#9]

**Comment by jerrytci** [comment]
谢谢你！


你尝试编译用本地的吧，教程readme有。被google下架了。我最近都没时间和心思搞这个插件。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rejerry/bookmark"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月14日(星期二) 晚上7:58
收件人:&nbsp;"rejerry/bookmark"<bookmark@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[rejerry/bookmark] 连不上了，老哥，看图片还蛮想用的 (#9)

**Comment by jerrytci** [comment]
> _No description provided._

已重新上线
